os:
  - osx
  - linux
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/gauge/gauge-deb nightly main'
    packages:
      - oracle-java8-set-default
      - maven
      - gauge
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install_latest_gauge_nightly.sh; fi
  - gauge version
  - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> $HOME/.gauge/config/gauge.properties
  - bundle install

language: ruby

rvm:
  - 2.3.0

script:
  - rake spec compile force_install
  - git clone --depth=1 https://github.com/getgauge/gauge-tests
  - cd gauge-tests
  - gauge install
  - TAGS="!unimplemented" ./starttests.sh ruby